# https://mc-back.onrender.com
# http://localhost:8080





### create coordinate
POST http://localhost:8080/coordinate/create
Content-Type: application/json

{
    "motoId": 1,
    "long": -34.34342,
    "lat": 56.14432,
    "speed": 120,
    "cap": "north"
}



### get all moto user
POST https://mc-back.onrender.com/coordinate/getallcoordmoto
Content-Type: application/json

{
    "motoId": 1
}



### get all history coordinate moto user
# 1278
POST https://mc-back.onrender.com/coordinate/getallhistorycoordmoto
Content-Type: application/json

{
    "motoId": 1
}




### delete all coordinates
DELETE http://localhost:8080/coordinate/deleteall
