# https://mc-back.onrender.com
# http://localhost:8080





### create moto
POST https://mc-back.onrender.com/moto/create
Content-Type: application/json

{
    "num_serie": "0001MG",
    "pseudo": "megafi kcc",
    "userId": 1
}



### get all moto user
POST https://mc-back.onrender.com/moto/getallmotouser
Content-Type: application/json

{
    "userId": 1
}




### get moto
POST https://mc-back.onrender.com/moto/get
Content-Type: application/json

{
    "motoId": 1
}



### update moto
POST http://localhost:8080/moto/update
Content-Type: application/json

{
    "id": 1,
    "pseudo": "megafi kcc"
}




### on off moto
POST http://localhost:8080/moto/updatestatus
Content-Type: application/json

{
    "id": 1,
    "status": true
}



### vibration moto
POST https://mc-back.onrender.com/moto/updatevibration
Content-Type: application/json

{
    "id": 1,
    "isVibration": true
}




### delete moto
DELETE http://localhost:8080/moto/delete
Content-Type: application/json

{
    "motoId": 1
}




### get status moto
POST https://mc-back.onrender.com/moto/getstatus
Content-Type: application/json

{
    "id": 1
}


### get virabtion moto
POST https://mc-back.onrender.com/moto/getviration
Content-Type: application/json

{
    "id": 1
}
