# https://mc-back.onrender.com

###
POST http://1c1476acf823.ngrok-free.app/api/gps
Content-Type: application/json

{
    "voltage": 200
}

###
POST https://mc-back.onrender.com/api/gps
Content-Type: application/json

{
    "voltage": 200
}



###
POST https://w7d8rlv8-8080.uks1.devtunnels.ms/proxy-gps
Content-Type: application/json

{
    "latitude": 250,
    "longitude": 200
}



###
GET https://mc-back.onrender.com/api/vibration